# This workflow is set to look at all the links in the readme.md every six months. If there are any links that spit out a 404 or other error, it will get listed in the linkChecker summary, and the badge on the readme will state whether it's "passing" or "failing".

# If it is failing, you will need to access the latest Links action that was ran, remove/replace any links that return an error, and then manually run the workflow again.

# Any links that need to be ignored is in .lycheeignore. This includes repo-specific media like badges and images.

name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 */6 *" # Run every 6 months.

jobs:
  linkChecker:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Links
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: --verbose --no-progress './**/README.md' --max-concurrency 8 # Max concurrency is set low to deal with rate limit errors.